### ISSUE TITLE
Consider moving to using Open Street Map / Leaflet

### ISSUE THREAD

**Issue by muloka** [tempranova/Native-Land#3]
I feel that this choice would be aligned with the spirit of this project as it is a community driven project. People continuously contribute to this project in good faith and used in positive ways. Most recently exemplified by the volunteers who worked tirelessly on mapping the affected areas of Nepal after the earthquake.
### Resources
- [http://www.openstreetmap.org/about](http://www.openstreetmap.org/about)
- [http://leafletjs.com/](http://leafletjs.com/)

**Comment by tempranova** [comment]
Finally following up on this... I'm definitely going to switch over as soon as I can. Expect more updates in the next month or so.

**Comment by eldang** [comment]
Do you want help with this?  I've just learned about this project and would love to help out - this issue is the sort of thing I have experience with.

**Comment by tempranova** [comment]
Hey Eldang! Yeah I have lots of experience moving things into Leaflet and stuff too, just no time to do that, always focused on adding new coordinates. But if you would be into whipping up a version that has the various interface elements working the same, that would be pretty rad. Let me know what you need!

**Comment by eldang** [comment]
:+1: I will have time, at least next week.  I'll make a fork, play around with it and see if I get stuck.

**Comment by eldang** [comment]
Hello again!  Sorry this has been a little longer than I said.  I see that the Google API is a bit more tightly integrated in this project than I'd realised - I was thinking it was just the map display itself, but now I see that you're also using the Google JS API to draw polygons, etc.  Anyway, I'm underway now, and have a couple of quick questions for you:

1. Do you have a preference between locally hosting include files (e.g. leaflet.js and leaflet.css) or using the CDN links?  I see examples of both in the existing code; I'm happy to standardise on either.
2. Do you have an opinion on map tile styles?  I'm happy to either follow your suggestion, just pick one myself, or make up a little comparisons page with a few I like and see what you think of them.

**Comment by eldang** [comment]
One caveat I'm seeing: I don't _think_ that we can pick and choose features like country/state/province labels, like you've done with the Google API.  So if we want to not display them--which I see a good case for--I think we have to pick a tile style that doesn't include them.

**Comment by tempranova** [comment]
Hey man -- yeah, I totally understand the troubles, it is somewhat involved with all the searching and UI interface and stuff. Only reason I haven't done it myself. But I would like to do an interface revamp overall sometime in the next couple months.

Answers:
- No real preference regarding CDN / non-CDN. Probably I'll go with CDN if I'm standardizing things.
- Map tiles should be not overly stylistic, just as much "normal map" as possible while remaining free. For an example of some stuff I did in leaflet, check out the api page (https://native-land.ca/api/index.html). It's a mess of a thing I just threw together, but you can see the valid map tiles in the first examples (the embeds). As you can see further down the page, map tile servers can change and suddenly want an API key as well, so it's a bit touch and go. But feel free to use the one shown in the embeds there https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}
- Yeah, I really like having the option of removing the names from the layers. Haven't looked into it really deeply in Leaflet, but if it's not there, in the end it's alright. I don't know how many people actually use that feature anyway!

Thanks for your work on this eldang.

**Comment by eldang** [comment]
No worries!  Thanks for getting the whole thing out there a couple of years ago.

I'll use CDN links for anything I add/update, but not necessarily worry about changing any for the sake of it.

I'm pretty sure we are stuck with whatever the tile server gives us, but there are a lot of free styles available.  I think I can find something that fits the bill, and would also prefer not to have things like country names in there.  The borders might still be useful for people to find their spot, but settler country names seem a bit... contrary to the message I hope people get from this map.

**Comment by tempranova** [comment]
Sure, take a look around. Yeah I'm constantly adding new polygons and stuff, but I think I'm going to look into a full revision in React shortly. Have you written any code yet? I may just get something rolling in the next week or so.

**Comment by eldang** [comment]
I've only done very small things in my fork (mostly just upgrading to the latest Leaflet.js and tweaking things to see if I understand how they work), so if you're thinking of making bigger changes it may be better for me to put what I had going on hold.

**Comment by tempranova** [comment]
OK, I've moved things over into a React homepage using Leaflet now! Feel free to let me know any feedback or bugs you find in the rollout:) thanks!

**Comment by MKLau** [comment]
@tempranova This is a great tool, thanks for developing it! 

Also, I wanted to quickly chime in and mention that the view in iOS in Safari is covered by the search field. This is probably a Leaflet issue, but maybe there's an easy fix. 

Otherwise, the search works and the links to docs work for Massachusetts.

**Comment by tempranova** [comment]
Thanks for the note -- I'll get to those mobile fixes ASAP.

**Comment by eldang** [comment]
Thank you @tempranova!  I'm on vacation for the next couple of weeks, but I'll take a good look around after that.

**Comment by tempranova** [comment]
Mobile should be a lot easier to use now (added a minimizing button, let me know if you think it's obvious enough)

**Comment by MKLau** [comment]
Yep, looks good!
