### ISSUE TITLE
Location pin

### ISSUE THREAD

**Issue by goatandsheep** [tempranova/Native-Land#61]
Hi can you put down a location pin when the user searches? Otherwise when I search and I move the cursor onto the map by accident I lose my results. If you display the pin, I can at least hover over to the spot where the pin is on the map and get the results again. I'm thinking you could just [put a marker every time people search](http://leafletjs.com/reference-1.2.0.html#marker)

`L.marker([50.5, 30.5]).addTo(map);`

**Comment by goatandsheep** [comment]
@tempranova why was this ticket closed?

**Comment by tempranova** [comment]
On the current site, the search doesn't affect the mouseover and vice versa:)
